[build]
  command = "npm install --legacy-peer-deps && NODE_ENV=production npm run build"
  publish = "/opt/build/repo/dist"


[build.environment]
  NODE_VERSION = "18.20.3"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200







